{
 "title": "Escalator",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "nodegroup",
    "label": "Node Group",
    "query": "label_values(node_group_nodes, node_group)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels, namespace)"
   },
   {
    "name": "cloud_provider_group",
    "label": "Cloud Provider Group",
    "query": "label_values(cloud_provider_size, id)"
   },
   {
    "name": "cloud_provider",
    "label": "Cloud Provider",
    "query": "label_values(cloud_provider_size, cloud_provider)"
   }
  ]
 },
 "panels": [
  { "title": "Heading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Escalator",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "content": "<span style=\"font-size: 3em; text-transform: uppercase; color: #2196F3\">\n  <b><center><span style=\"color: #FFF\">Escalator -</span> $nodegroup</center></b>\n</span>\n<span style=\"color: #2196F3\">\n  <center>\n    <span style=\"color: #FFF\">Namespace:</span> <b>$namespace</b>\n    <span style=\"color: #FFF\">, Cloud Provider:</span> <b>$cloud_provider</b>\n    <span style=\"color: #FFF\">, Group:</span> <b>$cloud_provider_group</b>\n  </center>\n</span>"
  },
  { "title": "Utilisation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU %",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "escalator_node_group_cpu_percent{node_group=\"$nodegroup\"}"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "escalator_node_group_mem_percent{node_group=\"$nodegroup\"}"
    }
   ]
  },
  {
   "title": "Percent Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "escalator_node_group_cpu_percent{node_group=\"$nodegroup\"}",
     "legendFormat": "cpu %"
    },
    {
     "expr": "escalator_node_group_mem_percent{node_group=\"$nodegroup\"}",
     "legendFormat": "mem %"
    }
   ]
  },
  { "title": "Escalator Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Nodes (untainted/tainted/cordoned)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "escalator_node_group_cordoned_nodes{node_group=\"$nodegroup\"}",
     "legendFormat": "cordoned"
    },
    {
     "expr": "escalator_node_group_tainted_nodes{node_group=\"$nodegroup\"}",
     "legendFormat": "tainted"
    },
    {
     "expr": "escalator_node_group_untainted_nodes{node_group=\"$nodegroup\"}",
     "legendFormat": "untainted"
    }
   ]
  },
  {
   "title": "Running Pods $namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod Phase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\"}) by (phase)"
    }
   ]
  },
  { "title": "Cloud Provider", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Cloud Provider Size vs Node Group Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "escalator_cloud_provider_size{cloud_provider=\"$cloud_provider\", id=\"$cloud_provider_group\"}",
     "legendFormat": "Size"
    },
    {
     "expr": "escalator_node_group_nodes{node_group=\"$nodegroup\"}",
     "legendFormat": "Kubernetes Nodes"
    }
   ]
  },
  {
   "title": "Cloud Provider Target Size vs Node Group Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "escalator_cloud_provider_target_size{cloud_provider=\"$cloud_provider\", id=\"$cloud_provider_group\"}",
     "legendFormat": "Target Size"
    },
    {
     "expr": "escalator_node_group_nodes{node_group=\"$nodegroup\"}",
     "legendFormat": "Kubernetes Nodes"
    }
   ]
  }
 ]
}